# -*- coding: utf-8 -*-
"""4110E109_1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F1GoQV1IKFM_GoeAezFgjPRxnQeqiRS7
"""

x = 10+5
print(x)

x = 10-5
print(x)

x = x - 3
print(x)

x = x ** 3
print(x)

x=6
y=3
print(x / y)

x=5
y=2
print(x // y)

x = x // 3
print(x)

x = x ^ 3
print(x)

b = "Hello, World!"
print(b[2:])

a = "Hello, World!"
print(a.lower())

a = " Hello, World! "
print(a.strip()) # returns "Hello, World!"

a = "Hello, World!"
print(a.replace("H", "J"))

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)

thislist = ["apple", "banana", "cherry"]
thislist.insert(1, "orange")
print(thislist)

thislist = ["apple", "banana", "cherry"]
thislist.pop()
print(thislist)

thislist = ["apple", "banana", "cherry"]
i = 0
while i < len(thislist):
  print(thislist[i])
  i = i + 1

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

thislist = ["apple", "banana", ]
mylist = list(thislist)
print(mylist)

list1 = ["a", "b" , "c"]
list2 = [1, 5, 7]

for x in list2:
  list1.append(x)

print(list1)

thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.sort(key = str.lower)
print(thislist)

thislist = ["apple", "papaya", "cherry"]
thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)

thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 2004,
  "colors": ["red", "white", "green"]
}

print(thisdict)

car = {
"brand": "Ford",
"model": "Mustang",
"year": 2001
}

x = car.keys()

print(x) #before the change

car["color"] = "blue"

print(x) #after the change

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

thisdict["year"] = 2022

print(thisdict)

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
del thisdict["year"]
print(thisdict)

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 2022
}
mydict = dict(thisdict)
print(mydict)

child1 = {
  "name" : "Emil",
  "year" : 2004 
}
child2 = {
  "name" : "Tobias",
  "year" : 2007
}
child3 = {
  "name" : "Linus",
  "year" : 2011
}

child4 = {
  "name" : "Linus",
  "year" : 2019
}

myfamily = {
  "child1" : child1,
  "child2" : child2,
  "child3" : child3,
  "child4" : child4
}

print(myfamily)